Added new questions
ChiperSoft/InterviewThis pull request #27
Opened 2022-08-27 12:33 UTC by Prashant-Bhapkar

Added some new questions which will definitely help to know more about the company working culture, and many more.

2022-08-27 18:54 UTC, Twipped requested changes

2022-08-27 18:54 UTC, Twipped commented on README.md
> +  - Are Full Stack Developers responsible to design User Interface?
This is the same question as the three above it.

2022-08-27 18:54 UTC, Twipped commented on README.md
> +  - What is the Policy if laptop get break/corrupted?
```suggestion
  - What is the Policy if a laptop is broken or corrupted?
```

2022-08-28 04:08 UTC, Prashant-Bhapkar commented
Changes done on newly added questions.

2022-08-28 04:08 UTC, closed without merging